SET SQLFORMAT CSV

set termout on
prompt schema_objects.sql
set termout off

set termout on
prompt --audit_results/cdb_views.csv
set termout off
spool audit_results/cdb_views.csv
select * from CDB_views order by owner, view_name;
spool off

set termout on
prompt --audit_results/cdb_tables.csv
set termout off
spool audit_results/cdb_tables.csv
select OWNER,	TABLE_NAME,	TABLESPACE_NAME,	CLUSTER_NAME,	IOT_NAME,	STATUS,	PCT_FREE,	PCT_USED,	INI_TRANS,	MAX_TRANS,	INITIAL_EXTENT,	NEXT_EXTENT,	MIN_EXTENTS,	MAX_EXTENTS,
                PCT_INCREASE,	FREELISTS,	FREELIST_GROUPS,	LOGGING,	PARTITIONED,	IOT_TYPE,	TEMPORARY,	SECONDARY,	NESTED,	BUFFER_POOL,	FLASH_CACHE,	CELL_FLASH_CACHE,	ROW_MOVEMENT,
                GLOBAL_STATS,	USER_STATS,	DURATION,	SKIP_CORRUPT,	MONITORING,	CLUSTER_OWNER,	DEPENDENCIES,	COMPRESSION,	COMPRESS_FOR,	DROPPED	READ_ONLY,	SEGMENT_CREATED,	RESULT_CACHE,
                CLUSTERING,	ACTIVITY_TRACKING,	DML_TIMESTAMP,	HAS_IDENTITY,	CONTAINER_DATA,	INMEMORY,	INMEMORY_PRIORITY,	INMEMORY_DISTRIBUTE,	INMEMORY_COMPRESSION,	INMEMORY_DUPLICATE,
                DEFAULT_COLLATION,	DUPLICATED,	SHARDED,	EXTERNAL,	HYBRID,	CELLMEMORY,	CONTAINERS_DEFAULT,	CONTAINER_MAP,	EXTENDED_DATA_LINK,	EXTENDED_DATA_LINK_MAP,	INMEMORY_SERVICE,
                INMEMORY_SERVICE_NAME,	CONTAINER_MAP_OBJECT,	MEMOPTIMIZE_READ,	MEMOPTIMIZE_WRITE,	HAS_SENSITIVE_COLUMN,	ADMIT_NULL,	DATA_LINK_DML_ENABLED,	LOGICAL_REPLICATION,	CON_ID 
from CDB_tables 
order by owner, table_name;
spool off
